// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5CtDQF1fDrRyMkHKxz1H29-wT4YoIuXk',
    appId: '1:992873380243:web:818285538a59f977a21066',
    messagingSenderId: '992873380243',
    projectId: 'shopping-app-9dfc0',
    authDomain: 'shopping-app-9dfc0.firebaseapp.com',
    storageBucket: 'shopping-app-9dfc0.appspot.com',
    measurementId: 'G-7B4E9LMDK9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD_eA_-Iple5VqwXoLlOetlxlVtSp1pF8',
    appId: '1:992873380243:android:6d024bc2dbee17b6a21066',
    messagingSenderId: '992873380243',
    projectId: 'shopping-app-9dfc0',
    storageBucket: 'shopping-app-9dfc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzo8HLhHD0ToJAVczRsYkr-LjsUzFbjXo',
    appId: '1:992873380243:ios:c3b8eb3a25e91eb8a21066',
    messagingSenderId: '992873380243',
    projectId: 'shopping-app-9dfc0',
    storageBucket: 'shopping-app-9dfc0.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzo8HLhHD0ToJAVczRsYkr-LjsUzFbjXo',
    appId: '1:992873380243:ios:37d92c09e86df2f1a21066',
    messagingSenderId: '992873380243',
    projectId: 'shopping-app-9dfc0',
    storageBucket: 'shopping-app-9dfc0.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
